const DB_NAME='personal-ledger-v2:'+new URL('./',import.meta.url).pathname;
let database;
function open(){if(database)return database;database=new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{for(const name of ['events','pending','meta'])r.result.createObjectStore(name,{keyPath:name==='events'?'revision':name==='pending'?'requestId':'key'});};r.onsuccess=()=>{r.result.onversionchange=()=>r.result.close();resolve(r.result);};r.onerror=()=>reject(Error('Local storage is unavailable. Enable website storage or leave private browsing.'));});return database;}
const request=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
export async function load(){const db=await open(),tx=db.transaction(['events','pending','meta']);const [events,pending,meta]=await Promise.all(['events','pending','meta'].map(n=>request(tx.objectStore(n).getAll())));return{events,pending,meta:Object.fromEntries(meta.map(m=>[m.key,m.value]))};}
// A single transaction commits data, receipts, and import metadata together.
export async function commit(events,meta,pending=[]){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction(['events','meta','pending'],'readwrite');for(const e of events)tx.objectStore('events').put(e);for(const [key,value] of Object.entries(meta))tx.objectStore('meta').put({key,value});for(const c of pending)tx.objectStore('pending').put(c);tx.oncomplete=resolve;tx.onerror=()=>reject(Error('Could not save this import. Existing local data is unchanged. Check available device storage.'));tx.onabort=()=>reject(Error('Import was cancelled; previous data is unchanged.'));});}
export async function removePending(id){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('pending','readwrite');tx.objectStore('pending').delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
export async function clear(){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction(['events','pending','meta'],'readwrite');for(const n of ['events','pending','meta'])tx.objectStore(n).clear();tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}
